name: Update catalog

on:
  repository_dispatch:
    types: [catalog_released]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Update to latest @network-of-terms/network-of-terms-catalog
        run: npm install @network-of-terms/network-of-terms-catalog
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: 'feat: Bump network-of-terms-catalog'
          body: Update the Network of Terms catalog.
          commit-message: 'feat: Bump network-of-terms-catalog'
          token: ${{ secrets.PAT }}
